<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:ns0="http://www.primeton.com/userManageIntfcaeService" xmlns:soap11="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.primeton.com/userManageIntfcaeService" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="com.primeton.primetoner.sysadmin.userManageIntfcaeComposite.userManageIntfcaeComponent.userManageIntfcaeService" targetNamespace="http://www.primeton.com/userManageIntfcaeService">
  <wsdl:import location="userManageIntfcaeService_import1.wsdl" namespace="http://www.primeton.com/userManageIntfcaeService">
    </wsdl:import>
  <wsdl:binding name="userManageIntfcaeServiceBinding" type="tns:userManageIntfcaeService">
    <soap11:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="changeUserId">
      <soap11:operation soapAction=""/>
      <wsdl:input name="changeUserId">
        <soap11:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="changeUserIdResponse">
        <soap11:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="deleteUser">
      <soap11:operation soapAction=""/>
      <wsdl:input name="deleteUser">
        <soap11:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="deleteUserResponse">
        <soap11:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="insertUser">
      <soap11:operation soapAction=""/>
      <wsdl:input name="insertUser">
        <soap11:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="insertUserResponse">
        <soap11:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="updateUserInfo">
      <soap11:operation soapAction=""/>
      <wsdl:input name="updateUserInfo">
        <soap11:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="updateUserInfoResponse">
        <soap11:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="updateUserSql">
      <soap11:operation soapAction=""/>
      <wsdl:input name="updateUserSql">
        <soap11:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="updateUserSqlResponse">
        <soap11:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="userManageIntfcaeServiceService">
    <wsdl:port binding="tns:userManageIntfcaeServiceBinding" name="userManageIntfcaeServicePort">
      <soap11:address location="http://primetoner.primeton.com:8100/primetoner/userManageIntfcaeService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
