<%@page import="org.json.simple.JSONObject"%>
<%

commonj.sdo.DataObject[] budget  = (commonj.sdo.DataObject[]) request.getAttribute("budget");
if(budget.length!=0){
JSONObject budget1 = new JSONObject();
JSONObject q2 = new JSONObject();
q2.put("pcontamt", budget[1].getDouble("pcontamt"));
q2.put("scontamt", budget[1].getDouble("scontamt"));
q2.put("selfservcost", budget[1].getDouble("selfservcost"));
q2.put("pmsubfee", budget[1].getDouble("pmsubfee"));
q2.put("prosubfee", budget[1].getDouble("prosubfee"));
q2.put("inoutfee", budget[1].getDouble("inoutfee"));
q2.put("selfsalecost", budget[1].getDouble("selfsalecost"));
q2.put("nquosalecost", budget[1].getDouble("nquosalecost"));
q2.put("mcontamt", budget[1].getDouble("mcontamt"));
q2.put("receamt", budget[1].getDouble("receamt"));
q2.put("ptaxincome", budget[1].getDouble("ptaxincome"));
q2.put("mtaxincome", budget[1].getDouble("mtaxincome"));
q2.put("staxincome", budget[1].getDouble("staxincome"));
q2.put("psubfee", budget[1].getDouble("psubfee"));
q2.put("msubfee", budget[1].getDouble("msubfee"));
q2.put("ssubfee", budget[1].getDouble("ssubfee"));
q2.put("comashar", budget[1].getDouble("comashar"));
q2.put("comdshar", budget[1].getDouble("comdshar"));
q2.put("commshar", budget[1].getDouble("commshar"));
q2.put("startfee", budget[1].getDouble("startfee"));
q2.put("bsfee", budget[1].getDouble("bsfee"));
q2.put("rebate", budget[1].getDouble("rebate"));
q2.put("instock", budget[1].getDouble("instock"));
q2.put("outstock", budget[1].getDouble("outstock"));
q2.put("baddebts", budget[1].getDouble("baddebts"));
q2.put("servtax", budget[1].getDouble("servtax"));
q2.put("assetlose", budget[1].getDouble("assetlose"));
JSONObject q3 = new JSONObject();
q3.put("selfservcost", budget[2].getDouble("selfservcost"));
q3.put("pmsubfee", budget[2].getDouble("pmsubfee"));
q3.put("prosubfee", budget[2].getDouble("prosubfee"));
q3.put("inoutfee", budget[2].getDouble("inoutfee"));
q3.put("selfsalecost", budget[2].getDouble("selfsalecost"));
q3.put("nquosalecost", budget[2].getDouble("nquosalecost"));
q3.put("pcontamt", budget[2].getDouble("pcontamt"));
q3.put("scontamt", budget[2].getDouble("scontamt"));
q3.put("mcontamt", budget[2].getDouble("mcontamt"));
q3.put("receamt", budget[2].getDouble("receamt"));
q3.put("ptaxincome", budget[2].getDouble("ptaxincome"));
q3.put("mtaxincome", budget[2].getDouble("mtaxincome"));
q3.put("staxincome", budget[2].getDouble("staxincome"));
q3.put("psubfee", budget[2].getDouble("psubfee"));
q3.put("msubfee", budget[2].getDouble("msubfee"));
q3.put("ssubfee", budget[2].getDouble("ssubfee"));
q3.put("comashar", budget[2].getDouble("comashar"));
q3.put("comdshar", budget[2].getDouble("comdshar"));
q3.put("commshar", budget[2].getDouble("commshar"));
q3.put("startfee", budget[1].getDouble("startfee"));
q3.put("bsfee", budget[1].getDouble("bsfee"));
q3.put("rebate", budget[1].getDouble("rebate"));
q3.put("instock", budget[2].getDouble("instock"));
q3.put("outstock", budget[2].getDouble("outstock"));
q3.put("baddebts", budget[2].getDouble("baddebts"));
q3.put("servtax", budget[2].getDouble("servtax"));
q3.put("assetlose", budget[2].getDouble("assetlose"));
JSONObject q4 = new JSONObject();
q4.put("selfservcost", budget[3].getDouble("selfservcost"));
q4.put("pmsubfee", budget[3].getDouble("pmsubfee"));
q4.put("prosubfee", budget[3].getDouble("prosubfee"));
q4.put("inoutfee", budget[3].getDouble("inoutfee"));
q4.put("selfsalecost", budget[3].getDouble("selfsalecost"));
q4.put("nquosalecost", budget[3].getDouble("nquosalecost"));
q4.put("pcontamt", budget[3].getDouble("pcontamt"));
q4.put("scontamt", budget[3].getDouble("scontamt"));
q4.put("mcontamt", budget[3].getDouble("mcontamt"));
q4.put("receamt", budget[3].getDouble("receamt"));
q4.put("ptaxincome", budget[3].getDouble("ptaxincome"));
q4.put("mtaxincome", budget[3].getDouble("mtaxincome"));
q4.put("staxincome", budget[3].getDouble("staxincome"));
q4.put("psubfee", budget[3].getDouble("psubfee"));
q4.put("msubfee", budget[3].getDouble("msubfee"));
q4.put("ssubfee", budget[3].getDouble("ssubfee"));
q4.put("comashar", budget[3].getDouble("comashar"));
q4.put("comdshar", budget[3].getDouble("comdshar"));
q4.put("commshar", budget[3].getDouble("commshar"));
q4.put("startfee", budget[1].getDouble("startfee"));
q4.put("bsfee", budget[1].getDouble("bsfee"));
q4.put("rebate", budget[1].getDouble("rebate"));
q4.put("instock", budget[3].getDouble("instock"));
q4.put("outstock", budget[3].getDouble("outstock"));
q4.put("baddebts", budget[3].getDouble("baddebts"));
q4.put("servtax", budget[3].getDouble("servtax"));
q4.put("assetlose", budget[3].getDouble("assetlose"));
JSONObject q1 = new JSONObject();
q1.put("selfservcost", budget[0].getDouble("selfservcost"));
q1.put("pmsubfee", budget[0].getDouble("pmsubfee"));
q1.put("prosubfee", budget[0].getDouble("prosubfee"));
q1.put("inoutfee", budget[0].getDouble("inoutfee"));
q1.put("selfsalecost", budget[0].getDouble("selfsalecost"));
q1.put("nquosalecost", budget[0].getDouble("nquosalecost"));
q1.put("pcontamt", budget[0].getDouble("pcontamt"));
q1.put("scontamt", budget[0].getDouble("scontamt"));
q1.put("mcontamt", budget[0].getDouble("mcontamt"));
q1.put("receamt", budget[0].getDouble("receamt"));
q1.put("ptaxincome", budget[0].getDouble("ptaxincome"));
q1.put("mtaxincome", budget[0].getDouble("mtaxincome"));
q1.put("staxincome", budget[0].getDouble("staxincome"));
q1.put("psubfee", budget[0].getDouble("psubfee"));
q1.put("msubfee", budget[0].getDouble("msubfee"));
q1.put("ssubfee", budget[0].getDouble("ssubfee"));
q1.put("comashar", budget[0].getDouble("comashar"));
q1.put("comdshar", budget[0].getDouble("comdshar"));
q1.put("commshar", budget[0].getDouble("commshar"));
q1.put("startfee", budget[1].getDouble("startfee"));
q1.put("bsfee", budget[1].getDouble("bsfee"));
q1.put("rebate", budget[1].getDouble("rebate"));
q1.put("instock", budget[0].getDouble("instock"));
q1.put("outstock", budget[0].getDouble("outstock"));
q1.put("baddebts", budget[0].getDouble("baddebts"));
q1.put("servtax", budget[0].getDouble("servtax"));
q1.put("assetlose", budget[0].getDouble("assetlose"));
budget1.put("q1", q1);
budget1.put("q2", q2);
budget1.put("q3", q3);
budget1.put("q4", q4);
budget1.toString();
out.println("<script>parent.test('"+budget1+"')</script>"); 
}else{
	int budget1 = 0;
out.println("<script>parent.test('"+budget1+"')</script>");  
}

%>